export const QUESTION_META = {
  short_text:      { label: 'Short text',       icon: '✏️' },
  long_text:       { label: 'Long text',         icon: '📄' },
  multiple_choice: { label: 'Multiple choice',   icon: '☑️' },
  dropdown:        { label: 'Dropdown',          icon: '▾'  },
  rating:          { label: 'Rating',            icon: '⭐' },
  nps:             { label: 'NPS',               icon: '📊' },
  yes_no:          { label: 'Yes / No',          icon: '✅' },
  date:            { label: 'Date',              icon: '📅' },
  time:            { label: 'Time',              icon: '⏰' },
  file_upload:     { label: 'File upload',       icon: '📎' },
  phone:           { label: 'Phone number',      icon: '📞' },
  email:           { label: 'Email',             icon: '✉️' },
  number:          { label: 'Number',            icon: '🔢' },
  address:         { label: 'Address',           icon: '📍' },
  signature:       { label: 'Signature',         icon: '✍️' },
  ranking:         { label: 'Ranking',           icon: '↕️' },
  matrix:          { label: 'Matrix',            icon: '⊞'  },
  payment:         { label: 'Payment',           icon: '💳' },
  statement:       { label: 'Statement',         icon: '💬' },
  welcome_screen:  { label: 'Welcome screen',    icon: '👋' },
  thank_you_screen:{ label: 'Thank you screen',  icon: '🎉' },
};
